-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2025-07-17 01:42:33 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE fakulteti (
    fakultetid   NUMBER NOT NULL,
    fullname     VARCHAR2(100) NOT NULL,
    shortname    VARCHAR2(20)
);

ALTER TABLE fakulteti ADD CONSTRAINT fakulteti_pk PRIMARY KEY ( fakultetid );

CREATE TABLE grupi (
    groupid   NUMBER NOT NULL,
    name      VARCHAR2(10) NOT NULL,
    specid    NUMBER NOT NULL,
    kurs      NUMBER NOT NULL
);

ALTER TABLE grupi ADD CONSTRAINT grupi_pk PRIMARY KEY ( groupid );

CREATE TABLE izpiti (
    izpitid     NUMBER NOT NULL,
    subjectid   NUMBER NOT NULL,
    groupid     NUMBER NOT NULL,
    "Date"      DATE NOT NULL,
    type        VARCHAR2(10)
);

ALTER TABLE izpiti ADD CONSTRAINT izpiti_pk PRIMARY KEY ( izpitid );

CREATE TABLE katedri (
    katedraid    NUMBER NOT NULL,
    name         VARCHAR2(50) NOT NULL,
    fakultetid   NUMBER NOT NULL
);

ALTER TABLE katedri ADD CONSTRAINT katedri_pk PRIMARY KEY ( katedraid );

CREATE TABLE lecturers (
    lecturerid    NUMBER NOT NULL,
    titla         VARCHAR2(20) NOT NULL,
    firstname     VARCHAR2(30) NOT NULL,
    lastname      VARCHAR2(30) NOT NULL,
    lecturernom   VARCHAR2(5) NOT NULL,
    katedraid     NUMBER NOT NULL
);

ALTER TABLE lecturers
    ADD CONSTRAINT chk_lecturernom_format CHECK ( REGEXP_LIKE ( lecturernom,
                                                                '^10[0-9]{3}$' ) );

ALTER TABLE lecturers ADD CONSTRAINT lecturers_pk PRIMARY KEY ( lecturerid );

CREATE TABLE ocenki (
    gradeid      NUMBER NOT NULL,
    studentid    NUMBER NOT NULL,
    subjectid    NUMBER NOT NULL,
    lecturerid   NUMBER NOT NULL,
    grade        NUMBER NOT NULL,
    "Date"       DATE NOT NULL
);

ALTER TABLE ocenki
    ADD CONSTRAINT chk_grade_range CHECK ( grade BETWEEN 1 AND 6 );

ALTER TABLE ocenki ADD CONSTRAINT ocenki_pk PRIMARY KEY ( gradeid );

CREATE TABLE predmeti (
    subjectid   NUMBER NOT NULL,
    name        VARCHAR2(100) NOT NULL,
    semestur    NUMBER NOT NULL,
    specid      NUMBER NOT NULL
);

ALTER TABLE predmeti ADD CONSTRAINT predmeti_pk PRIMARY KEY ( subjectid );

CREATE TABLE programi (
    programid    NUMBER NOT NULL,
    groupid      NUMBER NOT NULL,
    subjectid    NUMBER NOT NULL,
    day          VARCHAR2(10) NOT NULL,
    hour         VARCHAR2(10) NOT NULL,
    lecturerid   NUMBER NOT NULL
);

ALTER TABLE programi ADD CONSTRAINT programi_pk PRIMARY KEY ( programid );

CREATE TABLE specialnosti (
    specid       NUMBER NOT NULL,
    name         VARCHAR2(100) NOT NULL,
    shortname    VARCHAR2(10) NOT NULL,
    fakultetid   NUMBER NOT NULL
);

ALTER TABLE specialnosti ADD CONSTRAINT specialnosti_pk PRIMARY KEY ( specid );

CREATE TABLE students (
    studentid           NUMBER NOT NULL,
    firstname           VARCHAR2(30) NOT NULL,
    lastname            VARCHAR2(30) NOT NULL,
    facnom              VARCHAR2(8) NOT NULL,
    form_na_obuchenie   VARCHAR2(20) NOT NULL,
    oks                 VARCHAR2(20) NOT NULL,
    priem               NUMBER NOT NULL,
    fakultetid          NUMBER NOT NULL,
    specid              NUMBER NOT NULL,
    groupid             NUMBER NOT NULL,
    semesturcount       NUMBER NOT NULL,
    kurs                NUMBER NOT NULL
);

ALTER TABLE students ADD CONSTRAINT students_pk PRIMARY KEY ( studentid );

CREATE TABLE users (
    userid      INTEGER NOT NULL,
    username    VARCHAR2(50) NOT NULL,
    password    VARCHAR2(100) NOT NULL,
    role        VARCHAR2(20) NOT NULL,
    relatedid   NUMBER NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( userid );

ALTER TABLE users ADD CONSTRAINT users__un UNIQUE ( username );

ALTER TABLE grupi
    ADD CONSTRAINT grupi_specialnosti_fk FOREIGN KEY ( specid )
        REFERENCES specialnosti ( specid );

ALTER TABLE izpiti
    ADD CONSTRAINT izpiti_grupi_fk FOREIGN KEY ( groupid )
        REFERENCES grupi ( groupid );

ALTER TABLE izpiti
    ADD CONSTRAINT izpiti_predmeti_fk FOREIGN KEY ( subjectid )
        REFERENCES predmeti ( subjectid );

ALTER TABLE katedri
    ADD CONSTRAINT katedri_fakulteti_fk FOREIGN KEY ( fakultetid )
        REFERENCES fakulteti ( fakultetid );

ALTER TABLE lecturers
    ADD CONSTRAINT lecturers_katedri_fk FOREIGN KEY ( katedraid )
        REFERENCES katedri ( katedraid );

ALTER TABLE ocenki
    ADD CONSTRAINT ocenki_lecturers_fk FOREIGN KEY ( lecturerid )
        REFERENCES lecturers ( lecturerid );

ALTER TABLE ocenki
    ADD CONSTRAINT ocenki_predmeti_fk FOREIGN KEY ( subjectid )
        REFERENCES predmeti ( subjectid );

ALTER TABLE ocenki
    ADD CONSTRAINT ocenki_students_fk FOREIGN KEY ( studentid )
        REFERENCES students ( studentid );

ALTER TABLE predmeti
    ADD CONSTRAINT predmeti_specialnosti_fk FOREIGN KEY ( specid )
        REFERENCES specialnosti ( specid );

ALTER TABLE programi
    ADD CONSTRAINT programi_grupi_fk FOREIGN KEY ( groupid )
        REFERENCES grupi ( groupid );

ALTER TABLE programi
    ADD CONSTRAINT programi_lecturers_fk FOREIGN KEY ( lecturerid )
        REFERENCES lecturers ( lecturerid );

ALTER TABLE programi
    ADD CONSTRAINT programi_predmeti_fk FOREIGN KEY ( subjectid )
        REFERENCES predmeti ( subjectid );

ALTER TABLE specialnosti
    ADD CONSTRAINT specialnosti_fakulteti_fk FOREIGN KEY ( fakultetid )
        REFERENCES fakulteti ( fakultetid );

ALTER TABLE students
    ADD CONSTRAINT students_fakulteti_fk FOREIGN KEY ( fakultetid )
        REFERENCES fakulteti ( fakultetid );

ALTER TABLE students
    ADD CONSTRAINT students_grupi_fk FOREIGN KEY ( groupid )
        REFERENCES grupi ( groupid );

ALTER TABLE students
    ADD CONSTRAINT students_specialnosti_fk FOREIGN KEY ( specid )
        REFERENCES specialnosti ( specid );

ALTER TABLE users
    ADD CONSTRAINT users_lecturers_fk FOREIGN KEY ( relatedid )
        REFERENCES lecturers ( lecturerid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
